### ISSUE TITLE
Adding new properties breaks others' properties files

### ISSUE THREAD

**Issue by dfannius** [featurecat/lizzie#108]
I have a couple of pending pull requests that add new flags to `lizzie.properties`. To a brand-new user there is no problem because they have no properties file yet and `Config::createNewConfig` creates one for them with all valid properties, new and old. But if someone already has a properties file, the new properties won't get added to it automatically, and they'll get a crash at runtime trying to look one of them up.

I'm not sure what the best solution is. Probably the most robust one is to have `Config` read in the properties file, check that we have all of them, and if any are missing, add the new ones with the appropriate defaults and write the properties file back out.

**Comment by bittsitt** [comment]
I was looking at this as well. I think the best is to have a default configuration, that is replaced with whatever is found in the properties file. I would think is a very common problem so that there is a solution somewhere that we can re-use.

I was also playing with the idea to have another property file where one can remember last folder used (when opening sgfs), last window size (I'm getting pretty tired of resizing it every time) etc. (This is a separate issue really)

**Comment by featurecat** [comment]
I like @bittsitt's idea. If no one else does this, hopefully I can do it before release. would make transition smoother
