### ISSUE TITLE
stable/dev branch

### ISSUE THREAD

**Issue by Ka-zam** [featurecat/lizzie#119]
Perhaps it would be helpful to add a branch for development and then merge back into stable when deemed fully tested? Tags could be added for releases.

**Comment by Ka-zam** [comment]
I just mean that you wouldn't necessarily need to tag every merge to master with a tag.

**Comment by bittsitt** [comment]
@featurecat : You added the next branch (which I've started using for PR), but my last three PRs were merged to master instead of next. Was that just a mistake on your side? Just wondering which branch to base my PRs on... :-)

**Comment by featurecat** [comment]
Oops no idea how that happened. I'll fix. thanks.

**Comment by featurecat** [comment]
will fix in morning... (11 hrs from now)!

**Comment by bittsitt** [comment]
I have a pretty good idea as I've done it a couple of times myself ;-)

**Comment by bittsitt** [comment]
@featurecat  Ugh.. I just discovered what happened, and it is all my fault. My next branch was created off master branch (next and master were at the same head so I didn't notice). Sorry about that!!! I've resubmitted score-mode, should be on next now. 

But, the pass_bug_fix ended up on master. Should also be on next (that is just one line, so easy to merge/cherry pick). Otherwise, people will experience strange things when trying out score mode
