### ISSUE TITLE
Winrate graph observed in the wild

### ISSUE THREAD

**Issue by bittsitt** [featurecat/lizzie#142]
Hanayeol: "Look at the graph! Look at the graph! Ke Jie is in trouble!!" 😁 Looking good folks!

![image](https://user-images.githubusercontent.com/38073282/39351827-0a53908a-4a03-11e8-8e81-d9e43ef1d978.png)

(Apologies for creating a new issue, but I thought this was fun :-) )

**Comment by hydrogenpi** [comment]
Lizzie is climbing fast. I warned Sabaki devs about it but they brushed it off. they were complacent and slow to innovate. 

By year end, no one on leela will be using sabaki anymore

**Comment by featurecat** [comment]
to be explicit about it, I'm not interested in competing with or replacing other software. I really like Sabaki, I'm just trying to develop a tool (Lizzie) that meets my own wishes for an ai-based go program.

**Comment by hydrogenpi** [comment]
I want my $80 back!

![image](https://user-images.githubusercontent.com/35181396/39401724-184e5a36-4b01-11e8-8aa4-7e19fe6a8f23.png)

**Comment by featurecat** [comment]
haha same... I also bought Crazystone. but I'm happy to support Remi (it's developer). it was a fun purchase :)

**Comment by hydrogenpi** [comment]
Yes "weights" is stronger than LZ, by several hundred elo. Here is my thoughts, since LZ is already a top pro, even if his next CS was way stronger it is no longer enough to bridge the gap and still be commerically successful when there are already free top pro level bots out there (LZ etc). 

And traditionally CS was never known for its UI either, remind me of windows 98 interface and no dpi scaling means horrible on 4k monitors etc. 

BTW when are you going to refactor and then switch over to electron and dump the java?

**Comment by featurecat** [comment]
we're sticking with Java for the foreseeable future. since this project is open source, anyone may port it to whatever they'd like. I would fully support anything that was truly better :)

**Comment by hydrogenpi** [comment]
![image](https://user-images.githubusercontent.com/35181396/39403591-4df0fca6-4b34-11e8-960a-d114b67cf828.png)

**Comment by featurecat** [comment]
I think TMFOG is more about the interface than it's AI. many users like it. anyway this is not constructive.

**Comment by hydrogenpi** [comment]
sorry about that, I was inspired by this chess video and wanted to do nostalgic comparisons

https://www.youtube.com/watch?time_continue=1&v=R3By_rdwxSg
