### ISSUE TITLE
Can you make it not open as full screen (white blank) as the default?

### ISSUE THREAD

**Issue by hydrogenpi** [featurecat/lizzie#144]
This one thing is really annoying because it always open full screen and then I have to resize it. And when it opens full screen its completely blank and white and only shows up when I resize it. Can you set the default default action to be not a completely full screen? The more common use case is a windowed less than full screen anyway!

- Another request : Please give a way to click a button on the main interface gui to reset the entire board to blank (instead of just a shortcut)... or at least something in settings configurable so that such a button on the gui can be triggered to be "on" and showing for those that prefer a button for hard reset of the board state. Often because of issues I'm having to completely close out of Lizzie and open it back, and again having to resize the gui etc etc... just not fun to have to mess with issue after issue like this. 

- We would like for there to be a way get  rid of one or  both of the side banners if not used, (to free up screen space) since I'm often not using the tree thing but in order to show the winnrate graph the space for the tree panel on the right is also carved out and making the main board smaller in terms of real estate.

On that note, the ability to modularly dock and undock individual aspects like a panel free floating would be best. Think of like how adobe photoshop used to be back in the day. This way I can resize the winrrate graph to make it larger and put it on the top or bottom of the screen insead of on the side and making the board seem smaaller due to the forced aspect ration thing etc

**Comment by featurecat** [comment]
full screen: odd, I don't have this issue. I always use lizzie full screen and it displays right away (on Ubuntu and Windows). Ideally this is configurable but personally I almost always maximize windows I'm using since I like large displays.

1) what are the issues that cause game state to be bugged? they should be fixed. that is the answer. but yes to having buttons

2) the board is created to be as large as possible. removing side banners will still not make the board larger. side panels are added after the board is already made. you can disable the side panels in the Config / shortcut buttons.. I'm not sure what you want.

final idea about docking / moving / locking components: yes :)

**Comment by hydrogenpi** [comment]
Also. an easy way to see the current move number at a glance? perhaps on the bottom right hand corner of the tree window

**Comment by OlivierBlanvillain** [comment]
I have a local branch with an addition config option to change the window size on startup, I will try to turn that into a PR at some point.

**Comment by OlivierBlanvillain** [comment]
Actually, fixed in #287.
