### ISSUE TITLE
superhuman 9 by 9 lz weight is out

### ISSUE THREAD

**Issue by hydrogenpi** [featurecat/lizzie#152]
can lizzie adopt it please

**Comment by aerisnju** [comment]
It is not difficult to adapt lizzie for it. Just change the board size and the star points drawing and it will be OK. I've already made a private 9x9 version of lizzie and I may submit a PR if you need it. The board size can be configured by the config file.
But I'm afraid that it may create some confusions for users, because 9x9 leelaz does not share the same program or networks with the official 19x19 leelaz. Possibly we need some documents or explanations for the support.

**Comment by hydrogenpi** [comment]
can do a pr?

we need a multimode switch to go between diffrrent sizes and weights etc...

**Comment by Tenukis** [comment]
@aerisnju 
Please submit your private 9x9 version, it would be great.

**Comment by aerisnju** [comment]
@hydrogenpi 
> we need a multimode switch to go between diffrrent sizes and weights etc...

It requires more work to do that. The program and network weights of the official leelaz and the special 9x9 one are not the same nor interchangeable. Things would become easier if we implemented a program/network weights manager. But I can only provide a simple and preliminary 9x9 board support now.

**Comment by Tenukis** [comment]
@aerisnju
Is it possible to acces your modified lizzie to use the 9x9 board in config file?

**Comment by aerisnju** [comment]
@Tenukis 
I'll submit a PR to @featurecat  in a few days in this week. You can get it soon.

**Comment by OlivierBlanvillain** [comment]
Fixed in #252.
