### ISSUE TITLE
Release 0.5

### ISSUE THREAD

**Issue by bittsitt** [featurecat/lizzie#181]
I think there are enough fixes and features in place to warrant a 0.5 release?

**Comment by featurecat** [comment]
Yes. The last feature we will definitely need is automatic network downloading. I can't release until we add this since it caused so many issues. If anyone wants to add that, I'll prepare to release 0.5.

**Comment by featurecat** [comment]
Also, maybe this is the place to announce that I regret I haven't had the time yet to create a to-do list with priorities for contributing. I think I will finally have the time to dedicate to Lizzie after May 23rd, so I expect we can get a lot done later this month :). One of the top priorities I have is to refactor the code so that we can continue to make rapid progress, and to sort through the Issues and close/address any that are still open. I hope we can do this before long. I am thankful for all contributors.

Thanks to you, Lizzie has exploded with new interesting features in a short period of time, and the Go community now has this really amazing tool to increase Go knowledge. I think, especially with refactoring, we can develop Lizzie into a highly polished program that anyone can easily install and use: to play, to review games, and to explore!

**Comment by bittsitt** [comment]
Thumbs down? Really? Geez...
