### ISSUE TITLE
Restrict the search space

### ISSUE THREAD

**Issue by featurecat** [featurecat/lizzie#196]
It would be useful for joseki / fuseki / life and death analysis to restrict the search space of Leela Zero. Similar to ps.waltheris.net's search space selection feature. Leela Zero would be conscious of the rest of the board, but would only be allowed to make moves within the space defined by the user. We might implement this by making a GTP command for a custom version of Leela Zero:

    restrict_space <x_1> <y_1> <x_2> <y_2> # Confines search space to the rectangle bounded by the board coordinates (x_1, y_1) and (x_2, y_2)
    restrict_space reset # Lifts the search space restrictions

Lizzie would still be compatible with the default Leela Zero executable, especially when https://github.com/gcp/leela-zero/pull/1388 is merged. This would be an additional feature which would be shipped with Lizzie for windows users and compiled by Mac/Linux users, as we currently do.

**Comment by bittsitt** [comment]
Interesting idea. You could always ask if they would be willing to integrate it into Leela Zero? They might be...

The command should be on the from lz-<command> for extensions, so lz-restrict_space.

**Comment by dfannius** [comment]
I was thinking about this too, but wasn't sure how it should work in practice. LZ expands the tree like always but is only allowed to choose top-level moves from the restricted space? Or both sides are only "allowed" to play in the restricted space for all of the tree search?

The value and policy networks are always going to be outputting results that assume that both players can play anywhere at any time, both now and in the future. I think that any implementation that goes farther than "pick the best move, subject to it lying in the restricted space, with no further constraints on anyone's future moves" is going to run into situations where the network's output and the constraints we put on the search are going to be fighting each other in some way. (Imagine for example a ladder that LZ is not allowed to actually play out because it runs out of the restricted space.) I have no idea how much any of these issues are going to cause a problem in practice though.

**Comment by OlivierBlanvillain** [comment]
I don't think this is actionable on our side. Reopen if/when implemented in Leela Zero?
