### ISSUE TITLE
2  simple ideas to make lizzie better! 

### ISSUE THREAD

**Issue by hydrogenpi** [featurecat/lizzie#29]
1) I like in v03 you have the variations while hovering over! Could you optionally add the following; let use map a key (say CTRL) whereby if we hold it down and then mouse over then it gives the variations, but for any legal move that has branching variations it will show the most highest winrate first, but WHILE holding down the variation key (ie CTRL) and hovered over a legal move, if there are many different variations, the user can use the scroll of the mousewheel to instatly switch between variations so it shows all the different variations per that one move and it cycles graphically through them all, all the while numbering each variations! 

2) While moused over holding down the ALT key (or let us map it) will show the NEXT move by LZ AI as if the human player already made his move at that location of holding down the ALT key and hovering over the location... this saves time when playing "what if" and so no more need to constantly "go back" or "undo" etc... 

3) a way to dynamically adjust playout # on the fly... right now once I start a game in sabaki I can't change the playout until the next game. 

4) a way to side load multiple different nets and change/switch between them dynamically in game. or even during a game!

**Comment by featurecat** [comment]
1. I don't like this so much - if you're interested in a specific variation's branches, you should probably click it. That way you can guarantee that Leela Zero will invest 100% of its thinking time in the variation you're interested in; otherwise, it might only invest 20-30%.

2. I like this idea. It's a pretty minor shortcut optimization so it may make it into 0.4.

3. I've added a configuration option that lets you choose how many minutes Leela Zero will think until it stops pondering.

4. I will probably add this in a later version. Lizzie may have a ranked game mode, similar to Crazystone Mobile version, that automatically picks your opponent's level, in addition to an unranked game mode where you can decide your opponent/analysis network.

**Comment by hydrogenpi** [comment]
What about making Lizzie ability to import a Leela Zero Logfile and parse it to show the variations? This could be a great visualizer instead of reading the long sequences and multiple variations of the logs that LZ spits out.

**Comment by featurecat** [comment]
Sounds useful, but I'm not sure that many people actually use the logs...
