### ISSUE TITLE
A few minor suggestions

### ISSUE THREAD

**Issue by raspingbard** [featurecat/lizzie#291]
The latest 0.5 is a nice improvement!  Thanks for all the work.

1) I’d like to click on the move tree and go to that move.

2) There’s no visual feedback when Leela is thinking about playing a move.  I suggest replacing “Pondering off” with an appropriate message.

3) The Enter key doesn’t work consistently.  Sometimes it starts Leela playing moves.  Sometimes it makes Leela play only one move.  Sometimes is doesn’t do anything at all.

I’m running on Mac OS 10.13.4 with Java 10.0.1 and the latest LZ next branch.

**Comment by lephis** [comment]
Yup before seeing this post, I wanted to make here the same suggestion 1 as raspingbard said. It's very useful to think over all variations.

In addition, when I hit the "s" key to save an SGF file, I hope Lizzie can save the whole tree with all branches I studied in the tree panel, instead of only the main single branch.
