### ISSUE TITLE
language problem

### ISSUE THREAD

**Issue by humuyan** [featurecat/lizzie#292]
![2018-06-06 16-50-59](https://user-images.githubusercontent.com/28784198/41027512-cf3c5e52-69a9-11e8-8634-34403daa4979.png)

**Comment by featurecat** [comment]
hmm :/ does this happen throughout the X menu too? I'm not familiar with the Chinese translations, but does your system have the correct chinese font installed? do you ever experience other problems? it might be the font I included with lizzie being used here...

**Comment by humuyan** [comment]
![2018-06-07 08-00-36](https://user-images.githubusercontent.com/28784198/41071106-e3139740-6a28-11e8-931a-90da2679247e.png)
So which font does lizzie use? Is there a language option?
And in this new version I don't know how to start the analysis... In v0.4 it will automatically start after launching the program

**Comment by aerisnju** [comment]
The font for displaying these hints is system specific. It is using the font that is detected and used by GUI controls of java runtime, such as labels.
Probably it is the problem of java runtime detecting fonts, not lizzie's fault. Because there are plenty of Linux distributions, and each distribution may have a different style to store the fonts(path and font names), the java runtime is not able to detect the system font correctly for all of the distributions. It has to use the fallback font if it cannot detect the system font. As the fallback font carried by java runtime does not support Chinese characters, you will see the problem.
Making a search on searching engines can give you some workarounds. And I think lizzie can also provide the setting of choosing display languages. I'll submit a PR if needed.

**Comment by humuyan** [comment]
And I have another problem
+ in this new version, leela zero is always loading and cannot start the analysis
+ however starting game against leela zero and forcing leela zero move works

**Comment by featurecat** [comment]
humuyan you should open a separate issue for that

**Comment by OlivierBlanvillain** [comment]
Please reopen with instructions on how to reproduce, there is nothing we can do from these two screenshots...
