### ISSUE TITLE
LZ high handicap problem solved, please incorporate into Lizzie, code diff here 

### ISSUE THREAD

**Issue by hydrogenpi** [featurecat/lizzie#313]
https://github.com/gcp/leela-zero/issues/1599

Can give pro nine handicap stones on strong enough hardware ( 8x V100)

**Comment by hydrogenpi** [comment]
We need a haylee rematch lol

**Comment by featurecat** [comment]
I don't think it could beat a pro at 9 stones. But exciting. I think all you need to do is compile it to use it? Am I wrong?

**Comment by nukee86** [comment]
There's link to the binary and it works with lizzie. I tested it on other bots and it goes surprisingly well.

**Comment by Crazyeight101** [comment]
The problem is not solved.  A potential work-around has been found, however it's still extremely unstable and crashes *a lot*

You'll want to wait a while for testing and debugging, and if it does finally get incorporated into Lizzie, you would want to make the functionality optional, as it will affect the behavior of the engine (without the consequences being understood) even at low or no handicap.

**Comment by alreadydone** [comment]
A new version is released which should eliminate most crashes. As long as the komi is automatically adjusted, there's nothing Lizzie needs to do (except maybe displaying the current komi), though I did ask before to be able to adjust komi in Lizzie. The behavior of the engine is not affected until winrate drops below 15% (10% for the earlier version).
