### ISSUE TITLE
Lizzie crashes when leela is compiled with OPENCL on Osx

### ISSUE THREAD

**Issue by GreenAsJade** [featurecat/lizzie#336]
I compiled leela with the default config and ran it from the command line - it seems to work.

However, if I run Lizzie with this leela, it crashes after the "waiting for load" (IE long wait then crash).

If I comment out #define USE_OPENCL and recompile, then Lizzie works

**Comment by featurecat** [comment]
that shouldn't affect lizzie. most likely Leela zero is crashing, not lizzie. Mac does have a problem with opencl and I'm not sure what the fix is, since I don't own a Mac. make sure Leela zero is crashing by running it command line "./leelaz -w network-weight-here" and have it generate some moves. if it does generate normal moves with opencl then it actually is lizzie's fault.

**Comment by featurecat** [comment]
and if it's Leela zero that crashes, post on their repository for a fix

**Comment by GreenAsJade** [comment]
Ah - I thought that just firing up leelaz was enough to eliminate it as the culprit, but sure enough when I do genmove black it crashes.
