### ISSUE TITLE
About displaying KataGo score leads

### ISSUE THREAD

**Issue by hope366** [featurecat/lizzie#755]
In the upper toolbar of lizzie, there is a setting item, View -> KataGo Settings -> Score Mean -> Score Lead or Score Lead + Komi.
Let's say you choose "Score Lead". Then press "I" key to change Komi's value in Game Info.
If Komi is between -150 and 150, this value is reflected on the board.
However, if the Komi value is less than or equal to -150.5 or greater than 150.5, the default Komi value will be applied.
In other words, it appears that lizzie is rejecting this operation.

The official SGF for official matches between pros in FOX GO is often Komi=650, but if you load this into lizzie, Komi=650 is ignored and the win rate starts at around 50% for both sides.
Komi=650 is a strange thing, but lizzie rejects it, which makes this strange thing hard to notice.

If you set the Score Mean information to "Score Lead + Komi", Komi=650 is reflected on the board as it is, and black starts with about 650 points leads.
Komi=650 means that black is at a disadvantage. But lizzie's board is the opposite, starting with a huge lead for black. This is odd.

**Comment by NTUST-MITLAB** [comment]
In the 0.7.4 only the information of Score Mean is shown below the winrate bar together with stdev information etc. which is hard to read. The Score Lead information should be more clearly displayed on the winRate Panel UI, like it used to in the middle, and perhaps even a bit bigger.

Also, the Score Lead info, and ScoreMean + Komi information should both be shown on the UI, instead of having to do mental math to get the estimated stone count (ScoreMean + Komi is the "raw" stone count estimation which reflects more accurately about the actual board situation).

**Comment by NTUST-MITLAB** [comment]
I was able to restore it by reverting this change on WinratePane for LizzieMain and LizzieFrame
https://github.com/featurecat/lizzie/commit/6a339f097917d0c6e22e8d688661d801aefc83bf
And set double curSM = Lizzie.leelaz.scoreMean;
Also changes the condition for the center scoreMean for drawString with
if (Lizzie.leelaz.isKataGo && validScore) {

I was thinking maybe we can use the new Katago output format with scoreSelfplay value to replace the original maxScoreMean, which has a different value compared to the scoreMean (scoreLead), based solely on the current playout self-play result and closer to the original meaning (the scoreLead is a more conservative and stable value directly from new neural network output prediction, unlike maxSelfplay which can change drastically if after certain playouts when better variations were found). But this would require a new string parser and quite a bit of rework.
