### ISSUE TITLE
Multi-language support?

### ISSUE THREAD

**Issue by isty2e** [featurecat/lizzie#79]
With the majority of Go players being asians, it seems natural to provide a language support for them.

Probably the in-application strings can be loaded from an external file, for the sake of ease of redistribution and user patches?

**Comment by aerisnju** [comment]
It is easy to implement this by `ResourceBundle` in Java. I'll make an PR in a few days with translation to Chinese.

**Comment by bittsitt** [comment]
What is best practice when you need to add a new string, add the english translation to all translation files, or only adding it to the english one?

**Comment by aerisnju** [comment]
I think possibly adding it only to the english one is enough. It may be tedious to add it to all translations files manually, especially when there are more translations in the future. Possibly we need some scripts or tools to synchronize the english one with each of other translation files automatically. If someone would like to contribute to translation, he should use the scripts/tools first to synchronize the strings and then translate the strings added.

**Comment by featurecat** [comment]
This is partially implemented. One problem we have right now is that translations get out of date when an English-speaking developer adds an English string but doesn't know the translation. We need to have a system that allows users to submit their own translations so that we can integrate them. Maybe we can read translations from a text file. That way users could change incorrect translations.

**Comment by OlivierBlanvillain** [comment]
I think this could be closed after #97. To make sure that translations do not get out of date we should add a test that check that every key in the English l10n file is also present in the other files.
