### ISSUE TITLE
No good way to explore variations anymore

### ISSUE THREAD

**Issue by dfannius** [featurecat/lizzie#94]
My old method of analyzing games:
 - load an SGF file
 - right-arrow through the game
 - if I want to explore a variation, I click a different move and try out the variation
 - then I return to node where I deviated, and right-arrow to continue with the game

With the current version, however, when I click a different move from the game, I am asked "Do you want undo?". If I answer "yes", the remaining game data is deleted. If I answer "no", my variation becomes the main branch of the game tree and the actual game becomes the variation. Neither is what I want.

It's not obvious to me what the use case is that made the implementer change the behavior to this, so I'm not sure how to satisfy both of our needs. Maybe the new behavior can exist only if the user is playing Leela Zero?

At some point in the future we'll probably want to the ability to reorder variations with hotkeys, which will make some of this a little less annoying.

**Comment by featurecat** [comment]
Oh yeah I don't like that either. I'll change it.

**Comment by bittsitt** [comment]
If we keep the variationtree display vertical, I think it makes sense to use up and down to move between moves, and right/left to move between variations. It will throw people off the first time, but I think they will get used to it quickly.

**Comment by featurecat** [comment]
Fixed. @bittsitt: that sounds great!

**Comment by dfannius** [comment]
The undo is gone, but newly-played variations are still promoted to the trunk of the tree, making them the main variation (this is because `BoardHistoryNode::addOrGoto` calls `nexts.add(0, node)` rather than the original `nexts.add(node)`. I personally would like to change this back to the old behavior, and maybe later add commands for promoting/demoting variations.

**Comment by bittsitt** [comment]
In my opinion there is still a bug somewhere. When you add a variation, the variatontree makes the new variation as the main line (the left most line). This is not according to normal convention (every other program I've seen). The main line is always the left most line, variations are added on the right to show that they are variations. As it is now, it is difficult to know if you are in the main line or not. 

A side effect is that you will not get an updated winrate graph for the variation. This is by design, I was planning to add an extra line in the winrate graph (in a different color e.g.) when you are in a variation (shown together with the main line).

I like the new layout by the way,  looks better with the bar around it.

**Comment by featurecat** [comment]
@Bitsitt that's what I was thinking was missing. It seems like we'll be here for another 1-2 days anyway, could you add it?

**Comment by featurecat** [comment]
Theoretically fixed. Thoughts?

**Comment by dfannius** [comment]
Looks good to me after playing around with it for 30 seconds.

**Comment by featurecat** [comment]
adding it to the winrate graph would make feel a lot better. Beyond that, adding the ability to switch between variations easily will be great

**Comment by dfannius** [comment]
I think we can close this and create new issues for anything else that comes up. Certainly all of my original complaints have been addressed.
